### ISSUE TITLE
Update UI images

### ISSUE THREAD

**Issue by frascuchon** [argilla-io/argilla#270]
Tutorials, documentation and blogs contains images or videos showing an old UI version.

It should be nice update all the references

**Comment by dvsrepo** [comment]
I have partially updated the huggingface tutorial because we are promoting it.

I will create a separate repo for images and GIFs so we don't need to change the URLs in each notebook ( this is what I currently do for GIFs but it's on my dvsrepo account). This way is only a matter of updating the IMG in that repo and we dont overload this repo

**Comment by frascuchon** [comment]
Ok, but this could bring problems with older versions, once this approach is adopted.

**Comment by dvsrepo** [comment]
I'm open to suggestions. What I would like to avoid is:

- keeping large files (~15-20MB GIFs) in the main repo
- being constrained to not updating/improving the images over time (for
example improving the images for the stable release).

It's true that we could have some mismatch for older versions, but we can
always keep some sort of versioning for when things really change in the UI
and we don't want to have those new images in past versions.

Again very open to any suggestions

**Comment by frascuchon** [comment]
I'm fine with keep images in a separate repo(maybe just a different branch could be enough). What I've remarked was just to keeping the same url for all versions could make mismatch in older versions.

Since it's just a documentation concern, maybe we could change the document generation process to address all of those "fringes".
