### ISSUE TITLE
Review pagination component

### ISSUE THREAD

**Issue by leiyre** [argilla-io/argilla#308]

**Comment by Amelie-V** [comment]
- Records per page: 1 - 5 - 10 - 20 - 50 (value by default=5)
- Hide "<prev button" in the first page and  "next> button" on  the last one.
- Integrate styles and copy

**Comment by Amelie-V** [comment]
<img width="594" alt="Captura de pantalla 2021-09-08 a las 14 16 17" src="https://user-images.githubusercontent.com/84135211/132507670-ff854ba8-e7dc-4d5c-9cd1-29eeb146b2ca.png">

**Comment by Amelie-V** [comment]
Por cierto puedes evaluar lo que te lleva activar next and prev button con el teclado por fa?

**Comment by frascuchon** [comment]
Some additional comments after @leiyre work:

- Use a "Loading animation" when page changes. Long query responses could works fine with for records refresh. 
- "Record: x of y" message when records per page = 1 instead of "Records: x-x of y"
- Limit token classification records per page to 20. When 50, page becomes useless

and ideally:

- Changes in records per page should not make a pagination reset. The new page should be page containing (all or part of) records loaded previously

what do u think @leiyre and @Amelie-V ?

**Comment by Amelie-V** [comment]
- loading anim : ok to add it
- "Record: x of y": I recommend "Records: x-x of y"
-  20 max : ok
- page containing: ok

**Comment by Amelie-V** [comment]
- reduce next and previous bt size 
- reduce square to 30px too

**Comment by Amelie-V** [comment]
![Captura de pantalla 2021-09-13 a las 16 16 22](https://user-images.githubusercontent.com/84135211/133100213-5a4d8ff2-8342-43c2-a1cd-50f5101f1e09.png)

**Comment by Amelie-V** [comment]
the small arrow inside the button should apply to the back bt too (SS)

**Comment by Amelie-V** [comment]
![Uploading Captura de pantalla 2021-09-14 a las 22.50.43.png…]()

**Comment by leiyre** [comment]
> the small arrow inside the button should apply to the back bt too (SS)

@Amelie-V I can't see the SS
