### ISSUE TITLE
Rubrix with Amazon OpenSearch Service?

### ISSUE THREAD

**Issue by justinaustin** [argilla-io/argilla#494]
Hello! This project looks great and I'm excited to try it out for our use case.

Do you know if Rubrix is compatible with the Amazon OpenSearch Service? I'm currently using that for my project since it's convenient with AWS. I've run into issues recently with the python `elasticsearch` client saying that opensearch is no longer supported, and I feel like that could be a problem with this as well.

Thank you!

**Comment by frascuchon** [comment]
Hi @justinaustin 

Yes! Rubrix can works with AWS opensearch service. The problem here is the python client elasticsearch library. 
Normally using rubrix docker installation there is no problems about that.

If you're launching rubrix using  python, you should verify the elasticsearch client version. Max supported version for OpenSearch service is 7.13.x

**Comment by justinaustin** [comment]
Thank you! I'm excited to try it out 😄
