### ISSUE TITLE
[BUG-UI/UX] required/optional differentiation for`Fields` are not represented in the dataset settings

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/argilla#5361]
**Describe the bug**

 required/optional `Fields` are not represented in the dataset settings
**To Reproduce**
1. Go to the settings

![image](https://github.com/user-attachments/assets/1f3f4f51-89b2-4882-9422-909c01883032)
![image](https://github.com/user-attachments/assets/d89232da-6fac-4a46-823a-21f483f7e40d)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by nataliaElv** [comment]
@davidberenstein1957 I think this is a feature request rather than a bug. 
The fix developed by @damianpumar looks good, but my feeling is it needs some more design from @Amelie-V or @leiyre. Right now the toggle is read-only although it looks exactly the same as other toggles, so the feeling is that something isn't working right as the toggle doesn't respond to my actions. 
I would propose to wait for a design on how this information should be displayed to the user before merging. Any thoughts or ideas welcome 😄

**Comment by davidberenstein1957** [comment]
> @davidberenstein1957 I think this is a feature request rather than a bug. The fix developed by @damianpumar looks good, but my feeling is it needs some more design from @Amelie-V or @leiyre. Right now the toggle is read-only although it looks exactly the same as other toggles, so the feeling is that something isn't working right as the toggle doesn't respond to my actions. I would propose to wait for a design on how this information should be displayed to the user before merging. Any thoughts or ideas welcome 😄

Yes, after syncing with @damianpumar, I realized it was not a bug but something that had not been implemented on purpose. Let's wait for the 2.1.0 release and potentially review and tackle the solution along with https://github.com/argilla-io/argilla/issues/5393
